name: stop_watch
description: A simple stop-watch.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.10.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  #custom
  neumorphic: ^0.4.0
  flushbar: ^1.10.4
  
  
  cupertino_icons: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  
  
  
  uses-material-design: true
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
